// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBPTableApi.AppDbContext;

#nullable disable

namespace NBPTableApi.Migrations
{
    [DbContext(typeof(AppDbContextSqlite))]
    [Migration("20251021101803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("NBPTableApi.Models.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExchangeRatesTableId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeRatesTableId");

                    b.ToTable("ExchangeRateItems");
                });

            modelBuilder.Entity("NBPTableApi.Models.ExchangeRatesTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExchangeRatesTableItems");
                });

            modelBuilder.Entity("NBPTableApi.Models.ExchangeRate", b =>
                {
                    b.HasOne("NBPTableApi.Models.ExchangeRatesTable", "ExchangeRatesTable")
                        .WithMany("Rates")
                        .HasForeignKey("ExchangeRatesTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeRatesTable");
                });

            modelBuilder.Entity("NBPTableApi.Models.ExchangeRatesTable", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
